version: '2'
services:
  import:
    extends:
      file: docker-compose.yml
      service: build    
    command: ["--config", "config.js", "--import"]

  live:
    extends:
      file: docker-compose.yml
      service: build    
    command: ["--config", "config.js"]
