version: '2'
services:
  import:
    extends:
      file: common.yml
      service: cmd    
    command: ["--config", "config.js", "--import"]

  live:
    extends:
      file: common.yml
      service: cmd    
    command: ["--config", "config.js"]
